export const BALATRO_KNOWLEDGE = `
## What Balatro is

Balatro (LocalThunk, 2024) is a poker-themed roguelike deckbuilder: play poker hands from a 52-card deck to beat escalating "blinds"; Jokers, consumables and vouchers bend the rules.

**Run structure.** A run is 8 Antes (Endless continues past 8). Each Ante has three blinds in order: **Small Blind** (1x base chips, reward $3), **Big Blind** (1.5x, $4), **Boss Blind** (2x, $5, plus a rule-breaking effect). White-stake base chips per Ante: 300, 800, 2000, 5000, 11000, 20000, 35000, 50000; Green/Purple stakes scale harder . Small and Big Blinds can be **skipped** for a **Tag** (you forfeit that blind's money and its shop). Boss Blinds cannot be skipped. Defaults: 4 hands, 3 discards, hand size 8, 5 Joker slots, 2 consumable slots, $4 starting money. Money earns interest: $1 per $5 held, capped at $5 (i.e. $25 held); Seed Money/Money Tree raise the cap.

**Scoring.** Score = Chips × Mult. Each played hand type has a base (e.g. High Card 5×1, Pair 10×2, Flush 35×4) that Planet cards level up. Scored cards add their chip value; Jokers add +Chips, +Mult, or ×Mult. Evaluation is left to right across Jokers and scored cards, so order matters for copy/retrigger Jokers. Flat +Mult wins early; only ×Mult and retriggers keep pace after Ante ~4. The IEEE-754 overflow at ~1e308 displays as **naneinf**; Plasma Deck (score = ((Chips+Mult)/2)²) needs only ~1e154 Mult to reach it.

**Shops.** After each non-skipped blind: 2 card slots (Overstock/Overstock Plus add up to 2 more), 1 voucher slot (restocks after each Boss), 2 booster-pack slots. Reroll costs $5, +$1 per reroll, resets each shop (Reroll Surplus/Glut reduce it). Card-slot pool weights: Joker 20, Tarot 4, Planet 4; playing cards only with Magic Trick, Spectrals only on Ghost Deck . Shop Joker rarity: 70% Common, 25% Uncommon, 5% Rare; Legendaries never appear in shops. Shop edition odds: Foil 2%, Holographic 1.4%, Polychrome 0.3%, Negative 0.3% (Hone ×2, Glow Up ×4) . Packs: Standard (playing cards), Arcana (Tarot), Celestial (Planet), Buffoon (Jokers), Spectral; sizes Normal (choose 1 of 3, $4), Jumbo (1 of 5, $6), Mega (2 of 5, $8). The first shop of a run always contains a Buffoon pack, but it is a normal 1-of-3 pack, not a Mega. Slang to normalize: "tarot pack" = Arcana, "planet pack" = Celestial, "joker pack" = Buffoon, "ghost pack" = Spectral, "playing card pack" = Standard.

**Vouchers (32, 16 pairs; tier 2 requires tier 1 bought, so earliest is Ante 2).** Overstock → Overstock Plus (shop slots); Clearance Sale → Liquidation (25%/50% off); Hone → Glow Up (edition rates); Reroll Surplus → Reroll Glut; Crystal Ball → Omen Globe (+1 consumable slot; Spectrals in Arcana packs); Telescope → Observatory (Celestial packs contain your most-played hand's Planet; held Planets give ×1.5 to their hand); Grabber → Nacho Tong (+hands); Wasteful → Recyclomancy (+discards); Tarot Merchant → Tarot Tycoon; Planet Merchant → Planet Tycoon; Director's Cut → Retcon (reroll boss once per Ante $10 / unlimited); Paint Brush → Palette (+hand size); Magic Trick → Illusion (playing cards in shop, then with modifiers); Blank → Antimatter (nothing → +1 Joker slot); Seed Money → Money Tree (interest cap $10/$20); Hieroglyph → Petroglyph (Ante −1, costs a hand/discard; enables "ante 0").

**Consumables.** Tarot (22): The Fool (copy last Tarot/Planet), Magician (Lucky), High Priestess (2 Planets), Empress (Mult), Emperor (2 Tarots), Hierophant (Bonus), Lovers (Wild), Chariot (Steel), Justice (Glass), Hermit (double money, max $20), Wheel of Fortune (1 in 4 edition on a Joker), Strength (+1 rank), Hanged Man (destroy 2), Death (copy right card onto left), Temperance (Joker sell value, max $50), Devil (Gold), Tower (Stone), Star/Moon/Sun/World (3 cards to Diamonds/Clubs/Hearts/Spades), Judgement (random Joker). Planet (12): Pluto High Card, Mercury Pair, Uranus Two Pair, Venus Three of a Kind, Saturn Straight, Jupiter Flush, Earth Full House, Mars Four of a Kind, Neptune Straight Flush, Planet X Five of a Kind, Ceres Flush House, Eris Flush Five. Spectral (18): Familiar/Grim/Incantation (destroy 1, add enhanced face cards/Aces/numbers), Talisman (Gold Seal), Aura (edition), Deja Vu (Red Seal), Trance (Blue Seal), Medium (Purple Seal), Ouija (one rank, −1 hand size), Sigil (one suit), Cryptid (2 copies of a card), Wraith (Rare Joker, money to $0), Immolate (destroy 5, +$20), Ankh (copy a random Joker, destroy the rest), Hex (Polychrome on a random Joker, destroy the rest), Ectoplasm (Negative on a Joker, −1 hand size), **The Soul** (Legendary Joker), **Black Hole** (all hands +1 level). The Soul has a 0.3% chance per card generated in Arcana and Spectral packs; Black Hole 0.3% in Celestial and Spectral packs. The game avoids offering a consumable you already hold unless you have Showman.

**Enhancements/Seals/Editions.** Enhancements: Bonus +30 chips, Mult +4, Wild (any suit), Glass ×2 (1 in 4 to shatter), Steel ×1.5 while held in hand, Stone +50 chips no rank/suit, Gold $3 if held at end of round, Lucky (1 in 5 +20 Mult, 1 in 15 $20). Seals: Red (retrigger once), Blue (Planet of the final hand if held), Gold ($3 when scored), Purple (Tarot when discarded). Editions: Foil +50 chips, Holographic +10 Mult, Polychrome ×1.5 Mult, **Negative** (+1 Joker slot; on consumables +1 consumable slot; the Negative card occupies no net space).

**Tags (24, skip rewards).** Uncommon/Rare Tag (free Uncommon/Rare Joker in next shop); Negative/Foil/Holographic/Polychrome Tag (the **next base-edition Joker in a shop** becomes free with that edition; the tag waits if none is present); Investment ($25 after next Boss); Voucher (extra voucher in next shop); Boss (reroll boss); Standard/Charm/Meteor/Buffoon (free Mega Standard/Arcana/Celestial/Buffoon pack); Ethereal (free Spectral pack); Handy ($1 per hand played this run); Garbage ($1 per unused discard); Coupon (next shop's initial items free); Double (copies the next tag chosen); Juggle (+3 hand size next round); D6 (rerolls start at $0); Top-up (up to 2 Common Jokers); Speed ($5 per skipped blind); Orbital (+3 levels to a random hand); Economy (double money, max +$40). Tags are attached to each Small/Big Blind at generation; blinds do not "grant" tags for winning. : Negative, Foil, Holographic, Polychrome, Standard, Meteor, Buffoon, Handy, Garbage, Ethereal, Top-up and Orbital have a minimum Ante of 2, so an "Ante 1 Negative Tag" filter should return nothing.

**Legendary Jokers (only via The Soul):** Canio (×Mult when a face card is destroyed; spelling "Caino" is wrong), Triboulet (×2 per scored King/Queen), Yorick (×1 per 23 discards), Chicot (disables Boss Blind effects), Perkeo (Negative copy of a random held consumable at end of shop).

**Decks (15).** Red +1 discard; Blue +1 hand; Yellow +$10; Green no interest, $2/hand and $1/discard left; Black +1 Joker slot, −1 hand; Magic (Crystal Ball, 2× The Fool); Nebula (Telescope, −1 consumable slot); Ghost (Spectrals in shop, starts with Hex); Abandoned (40 cards, no face cards); Checkered (26 Spades, 26 Hearts); Zodiac (Tarot Merchant, Planet Merchant, Overstock); Painted (+2 hand size, −1 Joker slot); Anaglyph (Double Tag per Boss defeated); Plasma (averaged scoring, blinds ×2); Erratic (random ranks/suits, the only deck where \`ErraticSuit\`/\`ErraticRank\` filters apply). "Challenge" is a mode, not a deck, and cannot be seeded.

**Boss Blinds (28; 23 regular, 5 Ante-8 finishers).** Debuffers: The Club/Goad/Window/Head (Clubs/Spades/Diamonds/Hearts), The Plant (face cards), The Pillar (cards played earlier this Ante). Restrictors: The Psychic (exactly 5 cards), The Eye (no repeat hand types), The Mouth (one hand type), The Needle (one hand). Hidden info: The House (first hand face down), The Wheel (1 in 7 face down), The Fish (draws face down), The Mark (face cards face down). Scalers: The Wall (4x chips), The Flint (halves base chips and mult). Others: The Ox ($0 if you play your most-played hand), The Tooth (−$1 per card played), The Arm (−1 hand level), The Hook (discards 2 after each play), The Manacle (−1 hand size), The Water (no discards), The Serpent (always draw 3 after play/discard). Finishers: Amber Acorn (flips/shuffles Jokers), Cerulean Bell (forces a card selected), Crimson Heart (disables a random Joker each hand), Verdant Leaf (all cards debuffed until you sell a Joker), Violet Vessel (3x chips).

**Stakes (8).** White base; Red no Small Blind money; Green faster blind scaling; Black Eternal stickers (can't sell/destroy, ~30%); Blue −1 discard; Purple faster scaling; Orange Perishable stickers (debuffed after 5 rounds); Gold Rental stickers ($3 per round). Stickers gate strategies: Eternal Invisible Joker/Luchador are useless; a Perishable scaler dies before paying off.

**Seeds and RNG.** A seed is 1–8 characters from \`1-9A-Z\` (no zero): 35⁸ ≈ 2.3 trillion seeds ****. Every random event is a pseudo-hash of (a string key + the seed), so each domain has its own independent stream: shop queue per Ante, pack contents, card draw, boss selection, tag selection, edition rolls, and "1 in X" probability rolls (Wheel of Fortune, Lucky cards, Glass) each advance only their own key. Shop queues are keyed by Ante: viewing/rerolling advances that Ante's queue, and 5 rerolls then 7 gives the same sequence as 7 then 5; skipping doesn't skip that Ante's queue. Player choices (buying, rerolling, opening packs) consume queue positions, so an analyzer shows the queue for a given set of choices and Blueprint's "buy" simulation advances it. Same seed + deck + stake + game version (1.0.0n, 1.0.1c, 1.0.1f) + same choices = same run. Unlocks matter: a locked card rolls over to something else on that profile, and Legendaries require having found a Soul once unseeded. \`src/modules/balatrots/enum/\` in Blueprint holds the exact PRNG key strings; never alter them.

## Seed-hunting strategy and terminology

- **God seed**: a seed whose queues line up for a specific build. Prioritise what makes the run (the legendary/engine + its ante window) and rank the rest.
- **The Soul / "soul card"**: the only Legendary source; hunt it in Arcana/Spectral packs (Mega packs = more cards = more 0.3% rolls). Perkeo can duplicate a held Soul.
- **negleg**: shorthand for "Negative Legendary" searches (Blueprint README mentions ~8M seeds/s on that filter).
- **Perkeo loops**: hold one Cryptid → Negative Cryptids every shop → duplicate Red-Seal Steel Kings into 90-card hands; hold Pluto + Observatory → (1.5)^N on High Card ("Observatory infinite"); Blueprint/Brainstorm on Perkeo multiplies the copies.
- **Baron + Mime** (Steel Kings, Red Seals): (1.5)^4 per King; plus Serpent boss + Burglar to draw the whole deck; the standard naneinf engine. Killed by **The Plant** (debuffs face cards) unless Director's Cut/Retcon is available.
- **Blueprint/Brainstorm copy**: Blueprint copies the Joker to its right, Brainstorm the leftmost. Copying the ×Mult (Photograph) beats copying the retrigger (Chad): Photo+Chad ×8, Blueprint-on-Photo ×64, Blueprint-on-Chad ×32. Order rule: enabler left of payoff (Midas Mask before Vampire).
- **PhotoChad**: Photograph + Hanging Chad, $9 for ×8; Glass ×64, Red Seal ×128–256.
- **Triboulet/Idol engine**: Sock & Buskin or Hanging Chad retriggers on Red-Seal Glass Kings/Queens; The Idol needs a homogenized deck (Death, Hanged Man, Cryptid, Trading Card).
- **Ankh / Invisible Joker / Showman**: Ankh copies one random Joker and destroys the rest (classic early double-Blueprint); Invisible Joker sold after 2 rounds duplicates a random Joker (only way to double a Legendary); Showman allows duplicates in shops/packs. Selling a Negative Joker while at the cap causes **slot debt** (over cap, can't buy).
- **Diet Cola / Double Tag stacking**: selling Diet Cola creates a Double Tag; Double Tags stack, so a pile of them cashed on a Negative Tag yields many free Negative Jokers (Anaglyph Deck does this natively).
- **Tarot looping**: hold Negative copies of all Tarots except Emperor/Fool/Judgement (no Showman) so Emperor always yields Fool + Judgement; Fool re-creates Emperor; each Judgement has 0.3% Negative chance. "150 negatives" screenshot build.
- **Chicot × Manacle**: multiple Chicots reportedly turn Manacle's −1 hand size into +1 [unverified].
- **Oops! All 6s "casino"**: doubles listed probability numerators (Bloodstone 1 in 2 → guaranteed, Glass breaks 50%, Wheel boss 2 in 7).
- **Vampire + Midas Mask**, **Merry Andy + Hit the Road**, **DNA + Hologram**, **Hack + Wee Joker/Fibonacci**: enabler → payoff pairs. Anti-pairs: Vampire + Glass, Madness/Ceremonial Dagger + Eternal, Ride the Bus + Sock & Buskin, Joker Stencil + full board.
- **Phase rule**: Antes 1–2 need an anchor (+Mult/+Chips: Joker, Sly, Half, Gros Michel); Antes 3–5 need scalers (Constellation, Green Joker, Ride the Bus, Hologram) acquired early enough to grow; Antes 6–8 need 2–3 ×Mult sources. A late Constellation is a trap.
- **Community seeds [unverified]**: ALEEB (all 5 Legendaries by Ante 3, no skips), 11Y68BMP (double Polychrome Brainstorm + Holo Perkeo Ante 1), MIPK41M6 (Ghost: only Rares and Spectral packs), DCVE28EC (Ghost: Perkeo in Ante 1 shop), 8Q47WV6K (skip both Ante 1 blinds: Triboulet then Perkeo from Mega Arcana packs), 7M1GURT (63 Wheel of Fortune fails), I3EFEF17 (Erratic: 25 Tens), LWQW78CB (early Baron+Mime), YR98CK4B (Negative Perkeo Ante 1); seed index: LEGEJS53 (double Rare Tag), CASHCASH (Spectral tags), GLASS/X3DISXVS (DNA), FULL (Joker Stencil), AYO (Ouija all Kings).

## JAML, Motely, seedfinder.app, and Blueprint

**Motely** is the C# seed-search engine (by tacodiva, commissioned by OptimusPi/pifreak): AVX-512 SIMD, 8 seeds per vector per thread, the fastest CPU searcher. **motely-wasm** is its browser/Node build; v11+ is NativeAOT-LLVM, single-threaded, no SharedArrayBuffer/COI worker, boot once. Blueprint currently pins \`motely-wasm ^26.0.0\` and \`jaml-ui ^4.6.0\`. Search runs client-side in the browser; the MCP server never runs a search. FIXES.md (v22 era) documents: \`Program.jamlyze(seed, deck, stake)\` returns shopQueue, packs[].items, grantedLegendaryJoker and tag-granted Jokers per ante (~1200 seeds/s headless); items are integers with a rarity-paged encoding — \`(v>>8)&0xF0 == 0x50\` marks a Joker, \`(v>>8)&0x0F\` is rarity (0 common, 4 uncommon, 8 rare, C legendary), \`v&0xFF\` indexes the rarity-specific enum, \`(v>>16)&0xFF\` is edition (0x80 Negative); e.g. Blueprint 0x5807, Brainstorm 0x5811, Perkeo 0x5C04. \`jaml-lang\` is the language server (diagnostics/completions/hover), not a compiler; \`jaml-codemirror\` wires it into CodeMirror 6; \`jaml-ui\` provides JamlIde/JamlGameCard components.

**JAML (Jimbo's Ante Markup Language)** is a strict YAML-shaped filter DSL validated at load (schema \`https://mcp.seedfinder.app/jaml.schema.json\`, generated from Motely DTOs; VS Code extension \`pifreak.jaml-language-support\`).
- Top-level keys: \`name\`, \`deck\`, \`stake\` (plus \`id\`, \`version\`, \`author\`, \`description\`), and clause groups \`must\` (hard gates), \`should\` (add \`score: N\`, summed to rank), \`mustNot\` (disqualifiers). At least one group required.
- Clause discriminators, PascalCase values: \`joker\` (150), \`rareJoker\`/\`uncommonJoker\`/\`commonJoker\` (same match plus a parse-time rarity check), \`legendaryJoker\` (Canio, Triboulet, Yorick, Chicot, Perkeo), \`voucher\` (32), \`tarotCard\` (22), \`spectralCard\` (18), \`planetCard\` (12), \`boss\` (28), \`tag\` (24), \`smallBlindTag\`/\`bigBlindTag\`, \`standardCard\` (with \`enhancement\`/\`seal\`/\`edition\`), and event keys (\`wheelStaysFlipped\`, \`bloodstoneTrigger\`, \`luckyMoney\`, \`businessPayout\`, \`parkingPayout\`, \`misprintMult\` with \`mult:N\`) whose value is a roll-index array with \`min\`/\`max\`.
- Shared props: \`antes: [..]\` (0–39; 0 via Hieroglyph), \`score\`, \`label\`, \`edition\` (Negative/Foil/Holographic/Polychrome), \`seal\`, \`enhancement\`, \`sources: {shopItems: [0-7], boosterPacks: [0-5], arcanaPacks, spectralPacks}\`, \`min\`.
- Defaults: a \`joker:\` clause with no \`sources:\` checks **shop slots only**; legendaries **never** match shopItems and must use \`legendaryJoker:\` with \`boosterPacks\` (or arcana/spectral pack) sources. Tier-2 vouchers can't appear before Ante 2.
- Names: \`JokerStencil\` (not Stencil Joker), \`EightBall\`/"8 Ball", \`OopsAll6s\`, \`TheSoul\`, \`BlackHole\`, \`DirectorsCut\`, \`GlowUp\`, \`NegativeTag\`, \`ThePlant\`, \`TheSerpent\`, \`VioletVessel\`; decks \`Red…Erratic\`; stakes \`White…Gold\`.
- **JUMMY** one-liners (\`Blueprint in antes 1 or 2\`, \`Eternal Blueprint in Ante 1\`, \`Perkeo in antes 1, 2, or 3\`) are shorthand for the same clause; they cannot express \`sources:\`.
- Tips from the docs: keep \`must\` short and early-ante (every clause is a SIMD gate; ten must-jokers = zero hits); push synergy pieces into \`should\` with weights (e.g. Baron must, Mime/Blueprint/Brainstorm/Telescope should); reserve \`mustNot\` for fatal counters like \`boss: ThePlant\` on a face-card build rather than "no Anaglyph". A validated-but-zero-hit filter is usually over-gated. Keyword seed search (e.g. seeds containing PIFREAK) is a search-provider feature, not a JAML key.

Example (from the corpus):
\`\`\`yaml
name: Perkeo — negative consumables
deck: Red
stake: White
must:
  - legendaryJoker: Perkeo
    antes: [1]
    sources: { arcanaPacks: [0, 1], spectralPacks: [0, 1] }
should:
  - spectralCard: Cryptid
    antes: [1, 2, 3]
    score: 45
  - joker: Blueprint
    antes: [1, 2]
    score: 40
\`\`\`

**seedfinder.app / MCP.** \`mcp.seedfinder.app/mcp\` (server "balatro-seed-oracle"; the earlier "balatro-seedfinder" had get_jaml_schema/validate_jaml/describe_filter/analyze_seeds/open_filter_editor) exposes learn_jaml → plan_seed_search → validate_jaml → show_seedfinder_app (loads a draft into the app editor), plus score_seeds/jamlyze_seeds/find_similar_seeds for known seeds, estimate_keyword_search, save_filter/list_filters/get_filter (Neon), save_seed/list_seeds, and community search parties that split the 2.3T keyspace by block range. Full-keyspace grinding runs on the user's CPU via motely-wasm. A past bug remounted the app iframe once per widget tool call; the fix is one stable \`ui://\` template per tool with data via notifications (MCP Apps, SEP-1865). "The Long Blind" is the Next.js/R3F frontend in the patch doc; \`BalatroSeedOracle.x64.2.0.0.exe\` is the older desktop searcher.

**Blueprint (this app).** "Blueprint – pifreak's version": a Vite + Mantine React fork of Blueprint (miaklwalker), itself derived from MathIsFun0's The Soul (\`immolate.js\`). It takes a seed, deck, stake and version and reconstructs the run per Ante: shop queue, vouchers, tags, boss blind, booster packs and their contents, with a "JAML Mapped" view, in-browser motely-wasm search, and TXT/CSV seed-list upload. "Buying" in the simulator advances the relevant queue so later shops/packs match the live game. The assistant should describe what a given Ante's queue shows, translate wishes into JAML using the rules above, and note unlock/version caveats when a user can't reproduce a seed.
`;
